export const imageWithPathAndExtension = {
  portraitSmall: `dummyimage/portrait_small.jpg`,
  portraitMedium: `dummyimage/portrait_medium.jpg`,
  portraitXlarge: `dummyimage/portrait_xlarge.jpg`,
  portraitFantastic: `dummyimage/portrait_fantastic.jpg`,
  portraitUncanny: `dummyimage/portrait_uncanny.jpg`,
  portraitIncredible: `dummyimage/portrait_incredible.jpg`,
  standardSmall: `dummyimage/standard_small.jpg`,
  standardMedium: `dummyimage/standard_medium.jpg`,
  standardLarge: `dummyimage/standard_large.jpg`,
  standardXlarge: `dummyimage/standard_xlarge.jpg`,
  standardFantastic: `dummyimage/standard_fantastic.jpg`,
  standardAmazing: `dummyimage/standard_amazing.jpg`,
  landscapeSmall: `dummyimage/landscape_small.jpg`,
  landscapeMedium: `dummyimage/landscape_medium.jpg`,
  landscapeLarge: `dummyimage/landscape_large.jpg`,
  landscapeXlarge: `dummyimage/landscape_xlarge.jpg`,
  landscapeAmazing: `dummyimage/landscape_amazing.jpg`,
  landscapeIncredible: `dummyimage/landscape_incredible.jpg`,
  detail: `dummyimage/detail.jpg`,
  fullSizeImage: `dummyimage.jpg`
};
